env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: '@typescript-eslint/parser'

extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/eslint-recommended',
]

rules:
  react/react-in-jsx-scope: 0
  no-unused-vars: 0

globals:
  React: true
  propTypes: true
  renderer: true
  shallow: true
  mount: true

parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 8
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'