export default {
  CHANGE_FILTER_BY_GENRE: `CHANGE_FILTER_BY_GENRE`,
  GET_MOVIE_LIST_BY_GENRE: `GET_MOVIE_LIST_BY_GENRE`,
  GET_MOVIES_REQUEST: `GET_MOVIES_REQUEST`,
  GET_MOVIES_SUCCESS: `GET_MOVIES_SUCCESS`,
  GET_MOVIES_FAILED: `GET_MOVIES_FAILED`,
};
