export default {
  CHANGE_FILTER_BY_GENRE: `CHANGE_FILTER_BY_GENRE`,
  GET_MOVIE_LIST_BY_GENRE: `GET_MOVIE_LIST_BY_GENRE`,

  GET_MOVIES: `GET_MOVIES`,
  REQUEST_MOVIES: `REQUEST_MOVIES`,
  REQUEST_MOVIES_SUCCEEDED: `REQUEST_MOVIES_SUCCEEDED`,
  REQUEST_MOVIES_FAILED: `REQUEST_MOVIES_FAILED`
};
