export default {
  CHANGE_FILTER_BY_GENRE: `CHANGE_FILTER_BY_GENRE`,
  GET_MOVIE_LIST_BY_GENRE: `GET_MOVIE_LIST_BY_GENRE`,
  START_LOADING: `START_LOADING`,
  STOP_LOADING: `STOP_LOADING`,
  GET_MOVIES_SUCCESS: `GET_MOVIES_SUCCESS`,
  GET_MOVIES_FAILED: `GET_MOVIES_FAILED`,
  TOGGLE_MOVIE_IN_LIST: `TOGGLE_MOVIE_IN_LIST`,
};
